"""add schma in tinyurl model 02

Revision ID: d1492fd42954
Revises: 937e6eaf94d3
Create Date: 2019-12-23 02:57:44.382137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1492fd42954'
down_revision = '937e6eaf94d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tinyurl', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('tinyurl', sa.Column('type', sa.String(length=10), nullable=True))
    op.add_column('tinyurl', sa.Column('url_key', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_tinyurl_url_key'), 'tinyurl', ['url_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tinyurl_url_key'), table_name='tinyurl')
    op.drop_column('tinyurl', 'url_key')
    op.drop_column('tinyurl', 'type')
    op.drop_column('tinyurl', 'timestamp')
    # ### end Alembic commands ###
